apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tyershop-tls
  namespace: apps
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homolog.tyershop.com`)
      kind: Rule
      services:
        - name: tyershop-frontend
          port: 80
      middlewares:
        - name: cloudflare-only
    - match: Host(`medusa.homolog.tyershop.com`)
      kind: Rule
      services:
        - name: tyershop-backend
          port: 9000
      middlewares:
        - name: cloudflare-only
    - match: Host(`api.homolog.tyershop.com`)
      kind: Rule
      services:
        - name: tyershop-api
          port: 3000
      middlewares:
        - name: cloudflare-only
    # produção: aguardando DNS de tyershop.com sair do Squarespace (185.133.35.22)
    # e apontar pra nossa VPS (167.88.44.4) — rota já preparada
    - match: Host(`tyershop.com`) || Host(`www.tyershop.com`)
      kind: Rule
      services:
        - name: tyershop-frontend
          port: 80
      middlewares:
        - name: cloudflare-only
  tls:
    certResolver: letsencrypt
